language: python
python:
  - "2.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # Anaconda explicitly confirmed that using MKL under an academic license on Travis CI is acceptable use
  - 'echo ''{"_license_version": "1.1", "company": "University of Montreal", "email": "bart.van.merrienboer@umontreal.ca", "end_date": "2015-10-09", "issued": "2014-10-09", "name": "Bart van Merrinboer", "packages": "numbapro mkl iopro", "product": "Academic", "qty": "1", "sig": "10888ae03f336cd98cb43c2659666dbb0a15cae009d9ba628b2d09d6182dabb57d213bc22e064af3a9d74c576fb6dbcae6d7343fc520f68ff02983e7060c7254", "vendor": "continuum"}'' >> ~/.continuum/license_academic_20141009155056.txt'
install:
  - conda create --yes -q -n py26 mkl python=2.6 cython=0.2 pillow numpy=1.6 numpydoc scipy=0.11 pytables=3.0 numexpr=2.2.2 nose=1.1 pyyaml sphinx argparse pyflakes pip
  - source activate py26
  - pip install -q git+git://git.assembla.com/jobman.git
  - pip install -q --no-deps git+git://github.com/Theano/Theano.git
  - pip install -q nose-exclude
  - python setup.py develop
env:
  - FLAGS=floatX=float64 PART="--exclude-dir=pylearn2/models"
  - FLAGS=floatX=float64 PART=pylearn2/models
  - FLAGS=floatX=float32 PART="--exclude-dir=pylearn2/models"
  - FLAGS=floatX=float32 PART=pylearn2/models
  - TEST_DOC=YES
script:
  - sh .travis.sh
